### ISSUE TITLE
Pluralize is not working correctly on attributes taxonomies

### ISSUE THREAD

**Issue by MTayyabHanif** [wp-graphql/wp-graphql-woocommerce#508] opened 2021-06-12 20:18 UTC
**Describe the bug**
The pluralize cannot convert every attribute to plural correctly.

**To Reproduce**
Create a product attribute named "OS". It will be generated with as "pa_os".
The single name for this attribute is "paOs" and the pluralize will also generate "paOs", which will throw the error 
`**Fatal error**: Uncaught GraphQL\Error\InvariantViolation: The pa_os taxonomy cannot declare the same value for "graphql_single_name" and "graphql_plural_name". in /wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php:471`

**Expected behavior**
The plural of paOs should be "paOs_s" ? I'm not sure but they cannot be the same.

**Plugin Versions**
- **WooGraphQL Version:** 0.8.1

**Comment by kidunot89** [comment] 2021-06-13 02:05
🤔 This has been quite the problem as of late. Maybe a different inflector library or naming convention.

An naming convention like 
```
single: AttributeName
plural: AttributeNameCollection
```

**Comment by kidunot89** [comment] 2021-06-14 19:36
Duplicate of #505

**Closed by kidunot89** 2021-06-14 19:36 UTC
Labels: bug
